# Generated by Django 4.2.1 on 2023-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salinity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flow', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Valves',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
            options={
                'unique_together': {('date', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('state', models.BooleanField()),
                ('running_time', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('date', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='Breakers',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
            options={
                'unique_together': {('date', 'idx')},
            },
        ),
    ]
